name: pokedex
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.5
  formz: ^0.6.0
  get_it: ^7.6.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
